apiVersion: v1
kind: Service
metadata:
  name: istiokeycloak
  labels:
    app: istiokeycloak
    service: istiokeycloak
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: istiokeycloak
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-istiokeycloak
  labels:
    account: istiokeycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-istiokeycloak-v1
  labels:
    app: istiokeycloak
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiokeycloak
      version: v1
  template:
    metadata:
      labels:
        app: istiokeycloak
        version: v1
    spec:
      serviceAccountName: account-istiokeycloak
      containers:
        - name: istiokeycloak
          image: docker.io/shadrachjabonir/istiokeycloak
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istiokeycloak-ingress
spec:
  rules:
  - host: "istiokeycloak.192.168.99.103.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: istiokeycloak
            port:
              number: 8080